export const GANYMEDE_QUESTIONS = [
  {
    type: 'true-false',
    id: 'quiz_ganymede_size',
    bodyId: 'ganymede',
    level: 'both',
    statement: {
      sv: 'Ganymedes är större än planeten Merkurius.',
      en: 'Ganymede is larger than the planet Mercury.',
    },
    correct: true,
    hint: {
      sv: 'Ganymedes är den största månen i solsystemet.',
      en: 'Ganymede is the largest moon in the solar system.',
    },
    explanation: {
      sv: 'Ja — Ganymedes diameter är ungefär 5 268 km, medan Merkurius diameter är 4 879 km. Ganymedes är alltså bredare än en hel planet, men kretsar runt Jupiter.',
      en: "Yes — Ganymede's diameter is about 5,268 km, while Mercury's is 4,879 km. Ganymede is wider than a whole planet, yet orbits Jupiter.",
    },
  },
  {
    type: 'multiple-choice',
    id: 'quiz_ganymede_magnetic',
    bodyId: 'ganymede',
    level: 'upper',
    question: {
      sv: 'Vad är unikt med Ganymedes bland alla månar i solsystemet?',
      en: 'What is unique about Ganymede among all moons in the solar system?',
    },
    options: [
      {
        key: 'A',
        sv: 'Det är den enda måne med flytande vatten på ytan',
        en: 'It is the only moon with liquid water on its surface',
      },
      {
        key: 'B',
        sv: 'Det är den enda måne med eget magnetfält',
        en: 'It is the only moon with its own magnetic field',
      },
      {
        key: 'C',
        sv: 'Det är den enda måne med atmosfär',
        en: 'It is the only moon with an atmosphere',
      },
    ],
    correct: 'B',
    hint: {
      sv: 'Det skapar ett unikt polarsken som kan ses från Jupiters omloppsbana.',
      en: "It creates a unique aurora that can be seen from Jupiter's orbit.",
    },
    explanation: {
      sv: 'Ganymedes är den enda måne i solsystemet med ett eget magnetfält, troligtvis skapat av en flytande järnkärna. Det skapar ett mini-polarsken ovanpå Jupiters enorma polarsken.',
      en: "Ganymede is the only moon in the solar system with its own magnetic field, likely generated by a liquid iron core. It creates a mini-aurora on top of Jupiter's enormous aurora.",
    },
  },
  {
    type: 'true-false',
    id: 'quiz_ganymede_ocean',
    bodyId: 'ganymede',
    level: 'upper',
    statement: {
      sv: 'Ganymedes har ett saltvattensbäv gömt under isen, precis som Europa.',
      en: 'Ganymede has a saltwater ocean hidden beneath its ice, just like Europa.',
    },
    correct: true,
    hint: {
      sv: 'Hubbleteleskopet har hittat tecken på havet genom att studera polarsken.',
      en: 'The Hubble telescope found evidence of the ocean by studying its auroras.',
    },
    explanation: {
      sv: 'Ja — ett globalt saltvatten­hav gömmer sig ungefär 800 km under Ganymedes yta. Hubble identifierade havet genom att se hur magnetfältet och polarskenet rörde sig.',
      en: "Yes — a global saltwater ocean hides about 800 km beneath Ganymede's surface. Hubble identified the ocean by observing how the magnetic field and aurora moved.",
    },
  },
] as const;
