/**
 * WHAT THIS FILE DOES
 * ===================
 * Shifts the selected constellation away from screen center using
 * camera.setViewOffset() — the same projection-matrix trick used in
 * PlanetViewportOffset.tsx. Does NOT move anything in 3D space.
 *
 * WHEN TO CHANGE THIS
 * -------------------
 * Do not edit this file. Edit X_OFFSET and Y_OFFSET values for each
 * constellation in constellationViewSettings.ts instead.
 *
 * COORDINATE SYSTEM
 * -----------------
 *   X_OFFSET > 0  →  constellation shifts RIGHT on screen
 *   X_OFFSET < 0  →  constellation shifts LEFT
 *   Y_OFFSET > 0  →  constellation shifts UP
 *   Y_OFFSET < 0  →  constellation shifts DOWN
 *
 * Only active in overview + cinematic mode with a constellation selected,
 * and only after travel completes (!isTraveling). Mutually exclusive with
 * PlanetViewportOffset (which only activates in close-view mode).
 */

import { useFrame, useThree } from '@react-three/fiber';
import { useEffect } from 'react';
import { PerspectiveCamera } from 'three';
import { getConstellationViewportOffset } from '../lib/constellationViewSettings';
import { useStore } from '../store/useStore';

export const ConstellationViewportOffset = (): null => {
  const get = useThree((s) => s.get);
  const size = useThree((s) => s.size);
  const selectedConstellation = useStore((s) => s.selectedConstellation);
  const viewMode = useStore((s) => s.viewMode);
  const navigationMode = useStore((s) => s.navigationMode);
  const isTraveling = useStore((s) => s.isTraveling);

  const enabled =
    selectedConstellation !== null &&
    viewMode === 'overview' &&
    navigationMode === 'cinematic' &&
    !isTraveling;

  useEffect(() => {
    return () => {
      const { camera, size: s } = get();
      if (!(camera instanceof PerspectiveCamera)) return;
      if (camera.view?.enabled) {
        camera.clearViewOffset();
        camera.aspect = s.width / s.height;
        camera.updateProjectionMatrix();
      }
    };
  }, [get]);

  useFrame(() => {
    const camera = get().camera;
    if (!(camera instanceof PerspectiveCamera)) return;

    if (!enabled || !selectedConstellation) {
      if (camera.view?.enabled) {
        camera.clearViewOffset();
        camera.aspect = size.width / size.height;
        camera.updateProjectionMatrix();
      }
      return;
    }

    const offset = getConstellationViewportOffset(selectedConstellation);
    const xPixels = offset.x * size.width;
    const yPixels = offset.y * size.height;

    if (Math.abs(xPixels) < 0.5 && Math.abs(yPixels) < 0.5) {
      if (camera.view?.enabled) {
        camera.clearViewOffset();
        camera.aspect = size.width / size.height;
        camera.updateProjectionMatrix();
      }
      return;
    }

    // Positive X_OFFSET = shift right → virtual viewport moves left → offsetX is negative.
    // Positive Y_OFFSET = shift up    → virtual viewport moves down → offsetY is positive.
    camera.setViewOffset(
      size.width,
      size.height,
      -xPixels,
      yPixels,
      size.width,
      size.height,
    );
  }, 1);

  return null;
};
