/**
 * Generated by `scripts/generate-texture-variants.mjs`. Do not edit by hand.
 *
 * Maps each source texture to its native longest edge and the downscaled
 * sizes that exist on disk. `native` is what tells a caller whether the
 * source itself already fits a cap -- without it, the top rung would pick a
 * downscaled variant for a texture it was supposed to load at full size.
 */

export type TextureVariantEntry = {
  readonly native: number;
  readonly sizes: readonly number[];
};

export const TEXTURE_VARIANTS: Readonly<Record<string, TextureVariantEntry>> = {
  '/textures/callisto/diffuse.webp': { native: 1800, sizes: [1024, 512] },
  '/textures/earth/clouds.webp': { native: 1024, sizes: [512] },
  '/textures/earth/diffuse.webp': { native: 2048, sizes: [1024, 512] },
  '/textures/earth/normal.webp': { native: 2048, sizes: [1024, 512] },
  '/textures/earth/roughness.webp': { native: 2048, sizes: [1024, 512] },
  '/textures/europa/diffuse.webp': { native: 4096, sizes: [2048, 1024, 512] },
  '/textures/ganymede/diffuse.webp': { native: 1800, sizes: [1024, 512] },
  '/textures/io/diffuse.webp': { native: 3600, sizes: [2048, 1024, 512] },
  '/textures/jupiter/diffuse.webp': { native: 2048, sizes: [1024, 512] },
  '/textures/mars/diffuse.webp': { native: 2048, sizes: [1024, 512] },
  '/textures/mars_surface.webp': { native: 1024, sizes: [512] },
  '/textures/mercury/diffuse.webp': { native: 2048, sizes: [1024, 512] },
  '/textures/moon/diffuse.webp': { native: 2048, sizes: [1024, 512] },
  '/textures/neptune/diffuse.webp': { native: 2048, sizes: [1024, 512] },
  '/textures/pluto/diffuse.webp': { native: 4096, sizes: [2048, 1024, 512] },
  '/textures/saturn/diffuse.webp': { native: 2048, sizes: [1024, 512] },
  '/textures/saturn/ring.webp': { native: 2048, sizes: [1024, 512] },
  '/textures/sun/diffuse.webp': { native: 2048, sizes: [1024, 512] },
  '/textures/titan/diffuse.webp': { native: 2000, sizes: [1024, 512] },
  '/textures/triton/diffuse.webp': { native: 2048, sizes: [1024, 512] },
  '/textures/uranus/diffuse.webp': { native: 2048, sizes: [1024, 512] },
  '/textures/venus/diffuse.webp': { native: 2048, sizes: [1024, 512] },
};
